# Uncomment the next line to define a global platform for your project
# platform :ios

target 'PetPlant_PT_2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PetPlant_PT_2

 pod 'FSCalendar'

end
